# Generated by Django 3.0.7 on 2022-05-06 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='price',
        ),
    ]
